dataset_root: "/path/to/data/objaverse"

train_list: "./data/objaverse/train_list.txt"
val_list: "./data/objaverse/val_list.txt"

train_n_samples_per_subset: 10000 
val_n_samples_per_subset: 50

sort_frames: False

image_height: 512
image_width: 512

sampling_interval: 1.0